DROP TABLE DB2ADMIN.CONSENTS;
DROP TABLE DB2ADMIN.TOKENS;

CREATE TABLE DB2ADMIN.CONSENTS (
    SUBJECT VARCHAR(200) NOT NULL,
    CLIENTID VARCHAR(200) NOT NULL,
    SCOPES VARCHAR(2000) NOT NULL,
    CONSTRAINT "PK_DB2ADMIN.CONSENTS" PRIMARY KEY ("SUBJECT", "CLIENTID")
);

CREATE TABLE DB2ADMIN.TOKENS (
    "KEY" VARCHAR(128) NOT NULL,
    TOKENTYPE SMALLINT NOT NULL,
    SUBJECTId VARCHAR(200),
    CLIENTID VARCHAR(200) NOT NULL,
    JSONCODE VARCHAR(30000) NOT NULL,
    EXPIRY TIMESTAMP NOT NULL,
    CONSTRAINT "PK_DB2ADMIN.TOKENS" PRIMARY KEY ("KEY", "TOKENTYPE")
);